version: "3.9" 
services:
  fritzBoxUnten:
    image: meifritzconnectorrr:latest
    container_name: fritzBoxUnten
    hostname: fritzBoxUnten
    restart: always
    environment:
      FRITZBOX_USER_NAME : ${FRITZBOX_1_USER_NAME}
      FRITZBOX_USER_PASSWORD : ${FRITZBOX_1_USER_PASSWORD}
      FRITZBOX_IP_ADDRESS     : ${FRITZBOX_1_IP_ADDRESS}
      FRITZBOX_IDENTIFIER    : ${FRITZBOX_1_IDENTIFIER}
      REFRESH_RATE_SMARTHOME_SECONDS : ${REFRESH_RATE_SMARTHOME_SECONDS}
      REFRESH_RATE_DEVICELIST_MINUTES: ${REFRESH_RATE_DEVICELIST_MINUTES}
      REFRESH_RATE_CONNECTION_MINUTES: ${REFRESH_RATE_CONNECTION_MINUTES}
      DATABASE_NAME          : ${DATABASE_NAME}
      DATABASE_USER          : ${DATABASE_USER}
      DATABASE_PASSWORD      : ${DATABASE_PASSWORD}
      DATABASE_HOST          : ${DATABASE_HOST}
      DATABASE_PORT          : ${DATABASE_PORT}
  fritzBoxOben:
    image: meifritzconnectorrr:latest
    container_name: fritzBoxOben
    hostname: fritzBoxOben
    restart: always
    environment:
      FRITZBOX_USER_NAME : ${FRITZBOX_2_USER_NAME}
      FRITZBOX_USER_PASSWORD : ${FRITZBOX_2_USER_PASSWORD}
      FRITZBOX_IP_ADDRESS     : ${FRITZBOX_2_IP_ADDRESS}
      FRITZBOX_IDENTIFIER    : ${FRITZBOX_2_IDENTIFIER}
      REFRESH_RATE_SMARTHOME_SECONDS : ${REFRESH_RATE_SMARTHOME_SECONDS}
      REFRESH_RATE_DEVICELIST_MINUTES: ${REFRESH_RATE_DEVICELIST_MINUTES}
      REFRESH_RATE_CONNECTION_MINUTES: ${REFRESH_RATE_CONNECTION_MINUTES}
      DATABASE_NAME          : ${DATABASE_NAME}
      DATABASE_USER          : ${DATABASE_USER}
      DATABASE_PASSWORD      : ${DATABASE_PASSWORD}
      DATABASE_HOST          : ${DATABASE_HOST}
      DATABASE_PORT          : ${DATABASE_PORT}


